function config = getConfig()
% GETCONFIG Get global configuration for truck platoon system
%
% Returns:
%   config - Structure containing all configuration settings
%
% Author: zplotzke
% Last Modified: 2025-02-19 15:56:45 UTC
% Version: 1.1.10

% Network configuration
config.network = struct(...
    'input_size', 16, ...
    'hidden_size', 100, ...
    'output_size', 4, ...
    'learning_rate', 0.001, ...
    'max_epochs', 100, ...
    'mini_batch_size', 32, ...
    'dropout_rate', 0.2, ...
    'activation_function', 'tanh', ...
    'optimizer', 'adam', ...
    'weight_decay', 0.0001, ...
    'gradient_clip', 5.0, ...
    'sequence_length', 50 ...
    );

% Trainer configuration
config.trainer = struct(...
    'batch_size', 32, ...
    'epochs', 100, ...
    'validation_split', 0.2, ...
    'learning_rate', 0.001, ...
    'optimizer', 'adam', ...
    'loss_function', 'mse', ...
    'early_stopping_patience', 10, ...
    'min_delta', 1e-4, ...
    'shuffle', true, ...
    'verbose', true, ...
    'checkpoint_dir', 'checkpoints/', ...
    'save_best_only', true, ...
    'max_queue_size', 10, ...
    'workers', 4 ...
    );

% Safety configuration
config.safety = struct(...
    'collision_warning_distance', 15.0, ...    % meters
    'emergency_decel_threshold', -4.0, ...     % m/s^2
    'min_following_time', 1.5, ...            % seconds
    'max_platoon_length', 100.0, ...          % meters
    'warning_timeout', 5.0, ...               % seconds
    'max_lateral_deviation', 0.3, ...         % meters
    'min_brake_pressure', 0.2, ...            % bar
    'reaction_time_threshold', 0.5, ...       % seconds
    'max_speed_difference', 5.0, ...          % m/s
    'min_safety_distance', 10.0, ...          % meters
    'collision_time_threshold', 3.0, ...      % seconds
    'emergency_brake_duration', 2.0, ...      % seconds
    'warning_levels', struct(...
    'info', 1, ...
    'warning', 2, ...
    'critical', 3, ...
    'emergency', 4 ...
    ) ...
    );

% Truck configuration
config.truck = struct(...
    'num_trucks', 4, ...
    'initial_spacing', 20.0, ...              % meters
    'max_velocity', 30.0, ...                 % m/s
    'max_acceleration', 2.0, ...              % m/s^2
    'max_deceleration', -4.0, ...             % m/s^2
    'max_jerk', 1.0, ...                      % m/s^3
    'length', 16.5, ...                       % meters
    'width', 2.55, ...                        % meters
    'height', 4.0, ...                        % meters
    'mass', 40000, ...                        % kg
    'engine_power', 400, ...                  % kW
    'brake_force', 60000, ...                 % N
    'drag_coefficient', 0.6, ...
    'rolling_resistance', 0.007, ...
    'wheel_radius', 0.5, ...                  % meters
    'gear_ratios', [14.4, 9.49, 6.65, 4.95, 3.34, 2.45], ...
    'transmission_efficiency', 0.95 ...
    );

% Simulation configuration
config.simulation = struct(...
    'time_step', 0.1, ...                     % seconds
    'max_simulation_time', 3600, ...          % seconds
    'random_seed', 42, ...
    'update_frequency', 10, ...               % Hz
    'visualization_enabled', true, ...
    'log_level', 'INFO', ...
    'save_interval', 300, ...                 % seconds
    'output_directory', 'simulation_results/', ...
    'scenario_file', 'default_scenario.json', ...
    'weather_enabled', false, ...
    'traffic_enabled', false, ...
    'fault_injection', struct(...
    'enabled', false, ...
    'probability', 0.001, ...
    'types', {'sensor', 'actuator', 'communication'} ...
    ), ...
    'metrics', struct(...
    'collect_interval', 1.0, ...          % seconds
    'save_to_file', true, ...
    'plot_realtime', false ...
    ) ...
    );

% Sonification configuration
config.sonification = struct(...
    'enabled', true, ...
    'volume', 0.8, ...
    'warning_sounds', struct(...
    'collision', 'collision_warning.wav', ...
    'emergency_brake', 'emergency_brake.wav', ...
    'distance', 'distance_warning.wav', ...
    'speed', 'speed_warning.wav' ...
    ), ...
    'min_interval', 0.5, ...                  % seconds
    'max_concurrent_sounds', 3, ...
    'priority_levels', struct(...
    'collision', 4, ...
    'emergency_brake', 3, ...
    'distance', 2, ...
    'speed', 1 ...
    ) ...
    );

% Communication configuration
config.communication = struct(...
    'protocol', 'TCP/IP', ...
    'port', 5000, ...
    'host', 'localhost', ...
    'timeout', 1.0, ...                       % seconds
    'retry_attempts', 3, ...
    'heartbeat_interval', 0.1, ...            % seconds
    'buffer_size', 1024, ...                  % bytes
    'encryption_enabled', true, ...
    'compression_enabled', true, ...
    'max_packet_size', 8192, ...              % bytes
    'qos_level', 1 ...
    );

% Visualization configuration
config.visualization = struct(...
    'window_size', [1280, 720], ...
    'refresh_rate', 30, ...                   % Hz
    'colors', struct(...
    'background', [1, 1, 1], ...
    'trucks', [0, 0.447, 0.741], ...
    'warnings', [0.850, 0.325, 0.098], ...
    'grid', [0.7, 0.7, 0.7] ...
    ), ...
    'display_metrics', true, ...
    'plot_trajectories', true, ...
    'show_safety_bounds', true, ...
    'animation_speed', 1.0 ...
    );
end